### ISSUE TITLE
Please update

### ISSUE THREAD

**Issue by AirLeMineral** [jesdicaDomo/Unicode-Bedrock-New#2]
I hope it will be updated soon, I really need it

**Comment by jesdicaDomo** [comment]
I will try to update it. If you have an icon size 18x18 I can update it for you.

**Comment by AirLeMineral** [comment]
> I will try to update it. If you have an icon size 18x18 I can update it for you.

Can you make Unicode work for online servers?

**Comment by jesdicaDomo** [comment]
You just need to put it in the resources pack server.

**Comment by jesdicaDomo** [comment]
Server install usage https://youtu.be/DOz0nD8pvnM
