### ISSUE TITLE
32x32

### ISSUE THREAD

**Issue by Steellgold** [jesdicaDomo/Unicode-Bedrock-New#5]
Do you know how it is possible to add unicodes in 32x32?

**Comment by Steellgold** [comment]
Or how use this, this is my code to generate Unicode Code and i have create 32x32 generator code but this give that
![image](https://user-images.githubusercontent.com/51505384/127237812-e9bb91ce-94b8-4786-888d-91bf9541ac76.png)

**Comment by jesdicaDomo** [comment]
Unicode is just a font with a 16x16 image inserted over it.

The picture you mean is just an upload on github.

**Comment by Steellgold** [comment]
no I made my unicodes in 32x32 and converted them

**Comment by jesdicaDomo** [comment]
Do you have an example to look at?

**Comment by Steellgold** [comment]
What as an example?

**Comment by PleederDGM** [comment]
> Do you know how it is possible to add unicodes in 32x32?

32x32 is not possible. Was determined by Mojang. If you increase the resolution, all of the icons also enlarge.
