### ISSUE TITLE
help! this resource pack is too good

### ISSUE THREAD

**Issue by DHJ1** [jesdicaDomo/Unicode-Bedrock-New#8]
i'd like to complain about how  good this resource pack is but i cant seem to find your discord handle anywhere.
if i can get your discord handle that would be lovely! thanks

sorry for the corny issue lol

**Comment by jesdicaDomo** [comment]
You can't install resource packs?

**Comment by DHJ1** [comment]
sorry for the odd issue, i have no problems,
the resource pack is excellent and i love your work so i wanted to reach out to you on discord but couldn't find your handle anywhere
it was simply a corny joke to get your attention :)
